### ISSUE TITLE
Success action is not propagated to other middleware

### ISSUE THREAD

**Issue by alexanderfrey** [svrcekmichal/redux-axios-middleware#51]
Hi,

I have a problem with asynchronous request and the succeeding success action not being passed on to the other middleware but being completely consumed by redux-axios-middleware.

I have a custom middleware that is taking care of access token handling and that is saving the access token on LOGIN_SUCCESS to a cookie. But the LOGIN_SUCCESS action does never reach the custom middleware. Can someone pls shed some light here ? From my understanding actions get passed through all middleware, right ?

Thanks for your help, 
Alexander

**Comment by svrcekmichal** [comment]
Hey, can you send code of your middleware, overall middleware setup and also store setup? Is LOGIN_SUCESS handled by redux store? Because if yes, than it has passed through all the middlewares, because the flow is:
```
dispatch(action) => middleware1 => middleware2 => middleware3 => reducers
```
If any middleware does not call next(action) it can stop action propagation, but this is bad practise

**Comment by nmaves** [comment]
I am going to close this issue as there as been no interaction for over a month. If this still an issue please reopen the issue.
